gabywald.terminal.server.ipadress=127.0.0.1
gabywald.terminal.server.name=localhost
gabywald.terminal.server.servername=localhost
gabywald.terminal.server.port.authentication=9991
gabywald.terminal.server.port.services=9999
gabywald.terminal.server.token.secretKey=yourSecretKey
gabywald.terminal.server.token.issuer=Gaby Wald

gabywald.terminal.server.commands.package=gabywald.terminal3.serverside.shell.commands
gabywald.terminal.server.commands.list=CatCommand;CdCommand;ClearCommand;CpCommand;EchoCommand;ExitCommand;HelpCommand;\
LsCommand;MkdirCommand;MvCommand;PwdCommand;RmCommand;RmdirCommand;TouchCommand;\
GrepCommand;SortCommand;TrCommand;WcCommand



