gabywald.terminal.title=Terminal Emulator V3
gabywald.terminal.client=Client
gabywald.terminal.client.useragent=User Agent 12345
gabywald.terminal.server=Server
gabywald.terminal.server.ipadress=127.0.0.1
gabywald.terminal.server.name=localhost
gabywald.terminal.server.servername=localhost
gabywald.terminal.server.authentication=authenticate
gabywald.terminal.server.mainservice=terminalemulator
gabywald.terminal.server.port.authentication=9991
gabywald.terminal.server.port.services=9999
gabywald.terminal.server.rest.token=token
gabywald.terminal.server.rest.transmission=terminal
gabywald.terminal.server.token.secretKey=yourSecretKey
gabywald.terminal.server.token.issuer=Gaby Wald

gabywald.terminal.user.username=user
gabywald.terminal.user.password=psswd
